### ISSUE TITLE
Output frame is corrupted for v3 release

### ISSUE THREAD

**Issue by HolyWu** [dubhater/vapoursynth-nnedi3#10]
```Python
import vapoursynth as vs
core = vs.get_core()

clip = a YUV420P8 video

clip = core.nnedi3.nnedi3(clip, field=1, pscrn=1, fapprox=12, opt=True)

clip.set_output()
```

[Processed frame with the above script](http://www.imagebam.com/image/a1fefa392401586)
[Processed frame with the above script but set `opt=False`](http://www.imagebam.com/image/33e6d8392401589)

CPU is Intel Xeon E3-1231 v3. Since leaving `pscrn` and `fapprox` at their defaults doesn't incur this issue even though `opt=True`, I guess it's caused by FMA3 code path?

**Comment by dubhater** [comment]
Indeed, I screwed up there.
