### ISSUE TITLE
Port field order modes "-1" and "-2" (automatic) from AviSynth plugin

### ISSUE THREAD

**Issue by sekrit-twc** [dubhater/vapoursynth-nnedi3#11]
Since VS pre-r27 has extended the _FieldBased property to distinguish TFF and BFF, please bring back the automatic field order modes from the AVS plugin. It is not possible to process sources with varying field dominance without this support.

**Comment by dubhater** [comment]
Will do.

**Comment by myrsloik** [comment]
https://github.com/vapoursynth/vapoursynth/commit/4cf18204a95e00f52ce2ec7cb9ab8129b38819bf <- how I did it in eedi3, should be an identical change

**Comment by myrsloik** [comment]
Changed it a bit more so fins the latest revision to look at when you poke it.
