### ISSUE TITLE
_FieldBased is unchanged after running

### ISSUE THREAD

**Issue by AzraelNewtype** [dubhater/vapoursynth-nnedi3#13]
After deinterlacing, _FieldBased is still set to whatever it was on the way in, despite now being progressive. The property should either be set to zero or deleted, otherwise filters that check for interlacing based on the property (such as the internal resize filters) will all enforce interlaced rules.

**Comment by dubhater** [comment]
Sigh.

**Comment by dubhater** [comment]
Do you have an opinion about this? http://forum.doom9.org/showthread.php?p=1739196#post1739196
