### ISSUE TITLE
NNedi3 not behaving well in some edge cases with kanji

### ISSUE THREAD

**Issue by dscp46** [dubhater/vapoursynth-nnedi3#16]
Hi devs,

I've recently discovered your project and I've been quite impressed with the results nnedi3 has been producing overall.

However, I've noticed a few corner cases  on which it tends to perform under the competition, especially when there are horizontal features in some kanji, and in a specific case (refer to sample 2), some form of aliasing completely changed the character.  

For reference, here is the command line used to generate the following samples:
```bash
NNEDI_WEIGHTS="/usr/share/nnedi3/nnedi3_weights.bin"
ffmpeg -i ../source/A1_t00.mkv -color_primaries smpte170m -color_trc smpte170m -colorspace smpte170m -vf yadif -c:v libx265 -preset veryslow -crf 16 -x265-params aq-mode=3:aq-strength=0.9:psy-rd=1.2:deblock=-1,-1,level=4.1:colorprim=smpte170m:transfer=smpte170m:colormatrix=smpte170m:limit-sao=1 -pix_fmt yuv420p10le -c:a flac -compression_level 12 ep01.mkv
ffmpeg -i ../source/A1_t00.mkv -color_primaries smpte170m -color_trc smpte170m -colorspace smpte170m -vf nnedi=weights=${NNEDI_WEIGHTS}:nns=n128:pscrn=new3 -c:v libx265 -preset veryslow -crf 16 -x265-params aq-mode=3:aq-strength=0.9:psy-rd=1.2:deblock=-1,-1,level=4.1:colorprim=smpte170m:transfer=smpte170m:colormatrix=smpte170m:limit-sao=1 -pix_fmt yuv420p10le -c:a flac -compression_level 12 ep01_nnedi.mkv
```
### Sample 1
![Capture d’écran du 2024-04-07 03-53-44](https://github.com/dubhater/vapoursynth-nnedi3/assets/117170253/2acc359c-f8fa-449c-be23-4e8334c6de93)

![Capture d’écran du 2024-04-07 03-54-42](https://github.com/dubhater/vapoursynth-nnedi3/assets/117170253/dbb737a6-2552-4d01-bfe1-b8747c0fdc15)

### Sample 2
![Capture d’écran du 2024-04-07 03-55-24](https://github.com/dubhater/vapoursynth-nnedi3/assets/117170253/ba22bf64-3a57-43f1-bcc2-780938915197)

![Capture d’écran du 2024-04-07 03-55-57](https://github.com/dubhater/vapoursynth-nnedi3/assets/117170253/1d96b26b-bf09-45ad-9265-0acc729a33c5)

Should I try different settings, or might this need to re-generate the weights.bin file? How many samples would you need if applicable?

Kind regards

**Comment by dubhater** [comment]
I can't help you with that. I only copied the code and the weights from the original project: https://forum.doom9.org/showthread.php?t=147695 (thread by user "tritical" titled "nnedi2/nnedi3/eedi3").

**Comment by dscp46** [comment]
Thanks for the info, at least, I got a lead to follow (^^)
(in our specific case, I've figured out while comparing odd and even fields that the content was a 3:2 pulldown, so I ended up doing IVTC. Sorry for the noise)
